import type { DataSource } from '../../types';

export const GOVERNMENT_SOURCES: DataSource[] = [
  {
    id: 'mh-pwd-roads-bridges',
    name: 'Maharashtra Public Works Department — Roads & Bridges',
    type: 'official',
    tier: 'VERIFIED',
    url: 'https://pwd.maharashtra.gov.in/en/document-category/road-bridges/',
    status: 'active',
    trust_level: 1,
    last_checked: new Date().toISOString(),
    description: 'Official Maharashtra PWD source for roads and bridges information.',
    coverage: 'Maharashtra',
  },
  {
    id: 'msrdc',
    name: 'Maharashtra State Road Development Corporation',
    type: 'official',
    tier: 'VERIFIED',
    url: 'https://msrdc.in/',
    status: 'active',
    trust_level: 1,
    last_checked: new Date().toISOString(),
    description: 'Official MSRDC source for state road and bridge infrastructure.',
    coverage: 'Maharashtra',
  },
  {
    id: 'mh-water-supply',
    name: 'Maharashtra Water Supply and Sanitation Department',
    type: 'official',
    tier: 'VERIFIED',
    url: 'https://water.maharashtra.gov.in/',
    status: 'active',
    trust_level: 1,
    last_checked: new Date().toISOString(),
    description: 'Official Maharashtra government source for water supply and sanitation infrastructure.',
    coverage: 'Maharashtra',
  },
  {
    id: 'msedcl',
    name: 'Maharashtra State Electricity Distribution Company Limited',
    type: 'official',
    tier: 'VERIFIED',
    url: 'https://www.mahadiscom.in/',
    status: 'active',
    trust_level: 1,
    last_checked: new Date().toISOString(),
    description: 'Official MSEDCL source for electricity distribution infrastructure.',
    coverage: 'Maharashtra',
  },
  {
    id: 'msetcl',
    name: 'Maharashtra State Electricity Transmission Company Limited',
    type: 'official',
    tier: 'VERIFIED',
    url: 'https://www.mahatransco.in/',
    status: 'active',
    trust_level: 1,
    last_checked: new Date().toISOString(),
    description: 'Official MSETCL source for electricity transmission infrastructure.',
    coverage: 'Maharashtra',
  },
  {
    id: 'maha-state-data-bank',
    name: 'Maharashtra State Data Bank',
    type: 'official',
    tier: 'VERIFIED',
    url: 'https://www.mahasdb.maharashtra.gov.in/',
    status: 'active',
    trust_level: 1,
    last_checked: new Date().toISOString(),
    description: 'Maharashtra government data platform covering multiple infrastructure-related sectors.',
    coverage: 'Maharashtra',
  },
  {
    id: 'data-gov-in',
    name: 'Open Government Data Platform India',
    type: 'official',
    tier: 'VERIFIED',
    url: 'https://www.data.gov.in/',
    status: 'active',
    trust_level: 1,
    last_checked: new Date().toISOString(),
    description: 'Government of India open-data platform used as a supporting official data source.',
    coverage: 'India',
  },
];
